project:
  machine_name: bltd8
  prefix: BOLT
  human_name: 'BOLTd8'
  profile:
    name: lsp
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
  themes:
      - cog
  multisite:
    site1: { site-name: 'Site1 Development Site', site-mail: no-reply@acquia.com, account-name: admin, account-mail: no-reply@acquia.com, theme: cog }
    site2: { site-name: 'Site2 Dev', site-mail: no-reply@site2.com, account-name: admin, account-mail: no-reply@site2.com, theme: cog }
    default: { site-name: 'Site3 Dev', site-mail: no-reply@site3.com, account-name: admin, account-mail: no-reply@site3.com, theme: cog }
git:
  default_branch: master
  remotes:
    - git@github.com:jayakrishnanj/bolt.git
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
target-hooks:
  frontend-setup:
    dir: '${docroot}'
    command: 'echo ''No frontend-setup configured.'''
  frontend-build:
    dir: '${docroot}'
    command: 'echo ''No frontend-build configured.'''
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${deploy.dir}/docroot'
    command: 'echo ''No post-deploy build configured.'''
  post-setup-build:
    dir: '${docroot}'
    command: 'echo ''No post-setup build configured.'''
  post-deploy:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
import: '${repo.root}/blt/custom.xml'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acsf, acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acsf, acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acsf, acquia_connector, shield]
    uninstall: [devel, views_ui]
hosting: acsf
cm:
  strategy: features
multisite:
  name:
    - default
    - site1
    - site2
